theme: jekyll-theme-time-machine
# Name of your site (displayed in the header)
name: About Timo Rößner

# Short bio or description (displayed in the header)
description: I'm doing something with engineering. I guess.
